// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyHjF9EujEejh0C15dVgWamMCNpbLaGy8',
    appId: '1:498372485287:web:3d4f4d8c8c897e37f53b82',
    messagingSenderId: '498372485287',
    projectId: 'flutter-crud-119ce',
    authDomain: 'flutter-crud-119ce.firebaseapp.com',
    storageBucket: 'flutter-crud-119ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSpGCpGBTwToKTxMK9Qq6XSoIIhyLcaPk',
    appId: '1:498372485287:android:101f95485d5d49bcf53b82',
    messagingSenderId: '498372485287',
    projectId: 'flutter-crud-119ce',
    storageBucket: 'flutter-crud-119ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6B992VniihM1pY_NrJxramrA8UHkqdzU',
    appId: '1:498372485287:ios:c5b9d1eb8d1dd002f53b82',
    messagingSenderId: '498372485287',
    projectId: 'flutter-crud-119ce',
    storageBucket: 'flutter-crud-119ce.appspot.com',
    iosClientId: '498372485287-nremiqmbi47koqts0fivv88k2hp15atr.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactsCrudFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6B992VniihM1pY_NrJxramrA8UHkqdzU',
    appId: '1:498372485287:ios:c5b9d1eb8d1dd002f53b82',
    messagingSenderId: '498372485287',
    projectId: 'flutter-crud-119ce',
    storageBucket: 'flutter-crud-119ce.appspot.com',
    iosClientId: '498372485287-nremiqmbi47koqts0fivv88k2hp15atr.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactsCrudFlutter',
  );
}
